const data = {
  dataInfo: [
    { id: "1", original: "/gallery/1.webp", thumbnail: "/gallery/1.webp" },
    { id: "2", original: "/gallery/2.webp", thumbnail: "/gallery/2.webp" },
    { id: "3", original: "/gallery/3.webp", thumbnail: "/gallery/3.webp" },
    { id: "4", original: "/gallery/4.webp", thumbnail: "/gallery/4.webp" },
    { id: "5", original: "/gallery/5.webp", thumbnail: "/gallery/5.webp" },
    { id: "6", original: "/gallery/6.webp", thumbnail: "/gallery/6.webp" },
    { id: "7", original: "/gallery/7.webp", thumbnail: "/gallery/7.webp" },
    { id: "8", original: "/gallery/8.webp", thumbnail: "/gallery/8.webp" },
    { id: "9", original: "/gallery/9.webp", thumbnail: "/gallery/9.webp" },
    { id: "10", original: "/gallery/10.webp", thumbnail: "/gallery/10.webp" },
    { id: "11", original: "/gallery/11.webp", thumbnail: "/gallery/11.webp" },
    { id: "12", original: "/gallery/12.webp", thumbnail: "/gallery/12.webp" },
    { id: "13", original: "/gallery/13.webp", thumbnail: "/gallery/13.webp" },
    { id: "14", original: "/gallery/14.webp", thumbnail: "/gallery/14.webp" },
    { id: "15", original: "/gallery/15.webp", thumbnail: "/gallery/15.webp" },
    { id: "16", original: "/gallery/16.webp", thumbnail: "/gallery/16.webp" },
    { id: "17", original: "/gallery/17.webp", thumbnail: "/gallery/17.webp" },
    { id: "18", original: "/gallery/18.webp", thumbnail: "/gallery/18.webp" },
    { id: "19", original: "/gallery/19.webp", thumbnail: "/gallery/19.webp" },
    { id: "20", original: "/gallery/20.webp", thumbnail: "/gallery/20.webp" },
    { id: "21", original: "/gallery/21.webp", thumbnail: "/gallery/21.webp" },
    { id: "22", original: "/gallery/22.webp", thumbnail: "/gallery/22.webp" },
    { id: "23", original: "/gallery/23.webp", thumbnail: "/gallery/23.webp" },
    { id: "24", original: "/gallery/24.webp", thumbnail: "/gallery/24.webp" },
    { id: "25", original: "/gallery/25.webp", thumbnail: "/gallery/25.webp" },
    { id: "26", original: "/gallery/26.webp", thumbnail: "/gallery/26.webp" },
    { id: "27", original: "/gallery/27.webp", thumbnail: "/gallery/27.webp" },
    { id: "28", original: "/gallery/28.webp", thumbnail: "/gallery/28.webp" },
    { id: "29", original: "/gallery/29.webp", thumbnail: "/gallery/29.webp" },
    { id: "30", original: "/gallery/30.webp", thumbnail: "/gallery/30.webp" },
    { id: "31", original: "/gallery/31.webp", thumbnail: "/gallery/31.webp" },
    { id: "32", original: "/gallery/32.webp", thumbnail: "/gallery/32.webp" },
    { id: "33", original: "/gallery/33.webp", thumbnail: "/gallery/33.webp" },
    { id: "34", original: "/gallery/34.webp", thumbnail: "/gallery/34.webp" },
    { id: "35", original: "/gallery/35.webp", thumbnail: "/gallery/35.webp" },
    { id: "36", original: "/gallery/36.webp", thumbnail: "/gallery/36.webp" },
    { id: "37", original: "/gallery/37.webp", thumbnail: "/gallery/37.webp" },
    { id: "38", original: "/gallery/38.webp", thumbnail: "/gallery/38.webp" },
    { id: "39", original: "/gallery/39.webp", thumbnail: "/gallery/39.webp" },
    { id: "40", original: "/gallery/40.webp", thumbnail: "/gallery/40.webp" },
    { id: "41", original: "/gallery/41.webp", thumbnail: "/gallery/41.webp" },
    { id: "42", original: "/gallery/42.webp", thumbnail: "/gallery/42.webp" },
    { id: "43", original: "/gallery/43.webp", thumbnail: "/gallery/43.webp" },
    { id: "44", original: "/gallery/44.webp", thumbnail: "/gallery/44.webp" },
    { id: "45", original: "/gallery/45.webp", thumbnail: "/gallery/45.webp" },
    { id: "46", original: "/gallery/46.webp", thumbnail: "/gallery/46.webp" },
    { id: "47", original: "/gallery/47.webp", thumbnail: "/gallery/47.webp" },
    { id: "48", original: "/gallery/48.webp", thumbnail: "/gallery/48.webp" },
  ],
};

export default data;
